#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}"

OUTPUT="student-lego-workflow.pdf"
BUILD_DIR="$(mktemp -d)"
trap 'rm -rf "${BUILD_DIR}"' EXIT

CHAPTERS=(
  00-course-context.md
  01-technology-primer-for-managers.md
  02-end-to-end-architecture.md
  03-group-work-organization.md
  04-installation-windows-macos.md
  05-system-overview.md
  06-lorawan-and-ttn.md
  07-ttn-cloud-setup.md
  08-generator-workflow.md
  09-firmware-architecture.md
  10-sensors-and-measurements.md
  11-analog-calibration.md
  12-build-test-troubleshoot.md
  13-raspberry-pi-setup.md
  14-mqtt-theory.md
  15-building-snodec-and-mqttsuite.md
  16-local-mqttbroker-and-bridge.md
  17-mariadb-storage-with-mqttcli.md
  18-dashboard-with-snodec.md
  19-power-and-deep-sleep.md
  20-running-services-and-final-test.md
  21-real-water-measurement-and-field-test.md
  22-final-presentation-and-conclusion.md
  23-student-tasks.md
)

# The Markdown filenames are numbered so they sort naturally in the repository.
# The visible PDF section numbers, however, are generated by Pandoc/LaTeX.
# Therefore this build step removes manual chapter numbers such as
# "# 04 — LoRaWAN and TTN Theory" and local subsection counters such as
# "## 3. LoRaWAN as a multi-layer system" before handing the text to Pandoc.
# It also removes standalone Markdown horizontal rules so the PDF does not
# contain inconsistent separator lines between some sections but not others.
for chapter in "${CHAPTERS[@]}"; do
  sed -E \
    -e 's/^# [0-9]{2}[a-z]? — /# /' \
    -e 's/^## [0-9]+\. /## /' \
    -e 's/^### [0-9]+\. /### /' \
    -e '/^---[[:space:]]*$/d' \
    "${chapter}" > "${BUILD_DIR}/${chapter}"
done

PANDOC_INPUTS=()
for chapter in "${CHAPTERS[@]}"; do
  PANDOC_INPUTS+=("${BUILD_DIR}/${chapter}")
done

pandoc \
  metadata.yaml \
  "${PANDOC_INPUTS[@]}" \
  --toc \
  --number-sections \
  --listings \
  --pdf-engine=xelatex \
  -o "${OUTPUT}"

echo "Created ${SCRIPT_DIR}/${OUTPUT}"
