#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}"

OUTPUT="student-lego-workflow.pdf"
BUILD_DIR="$(mktemp -d)"
trap 'rm -rf "${BUILD_DIR}"' EXIT

CHAPTERS=(
  00-course-context.md
  01-technology-primer-for-managers.md
  02-installation-windows-macos.md
  03-system-overview.md
  04-lorawan-and-ttn.md
  05-generator-workflow.md
  06-firmware-architecture.md
  07-sensors-and-measurements.md
  08-analog-calibration.md
  09-power-and-deep-sleep.md
  10-build-test-troubleshoot.md
  11-student-tasks.md
)

# The Markdown filenames are numbered so they sort naturally in the repository.
# The visible PDF section numbers, however, are generated by Pandoc/LaTeX.
# Therefore this build step removes manual chapter numbers such as
# "# 04 — LoRaWAN and TTN Theory" and local subsection counters such as
# "## 3. LoRaWAN as a multi-layer system" before handing the text to Pandoc.
for chapter in "${CHAPTERS[@]}"; do
  sed -E \
    -e 's/^# [0-9]{2}[a-z]? — /# /' \
    -e 's/^## [0-9]+\. /## /' \
    -e 's/^### [0-9]+\. /### /' \
    "${chapter}" > "${BUILD_DIR}/${chapter}"
done

pandoc \
  metadata.yaml \
  "${BUILD_DIR}/00-course-context.md" \
  "${BUILD_DIR}/01-technology-primer-for-managers.md" \
  "${BUILD_DIR}/02-installation-windows-macos.md" \
  "${BUILD_DIR}/03-system-overview.md" \
  "${BUILD_DIR}/04-lorawan-and-ttn.md" \
  "${BUILD_DIR}/05-generator-workflow.md" \
  "${BUILD_DIR}/06-firmware-architecture.md" \
  "${BUILD_DIR}/07-sensors-and-measurements.md" \
  "${BUILD_DIR}/08-analog-calibration.md" \
  "${BUILD_DIR}/09-power-and-deep-sleep.md" \
  "${BUILD_DIR}/10-build-test-troubleshoot.md" \
  "${BUILD_DIR}/11-student-tasks.md" \
  --toc \
  --number-sections \
  --pdf-engine=xelatex \
  -o "${OUTPUT}"

echo "Created ${SCRIPT_DIR}/${OUTPUT}"
