; PH4502C pH module
;
; Copy this section into platformio.ini or merge this module branch into a project branch.

[ph_ph4502c]
build_flags =
    -D PH4502C_PH_PIN=34
    -D PH4502C_TEMPERATURE_PIN=35
    -D PH10_ADC_VALUE=1615
    -D PH7_ADC_VALUE=2080
    -D PH4_ADC_VALUE=2503
    -D APP_CALIBRATE_PH_PIN=0
