; Gravity TDS module
;
; Copy this section into platformio.ini or merge this module branch into a project branch.

[tds_gravity]
build_flags =
    -D TDS_SENSOR_PIN=32
    -D A1=TDS_SENSOR_PIN
    -D TDS_SENSOR_VCC=3.3
    -D TDS_SENSOR_ADC_RESOLUTION=4096
lib_deps =
    https://github.com/PCo-IoT-2024/GravityTDS.git
    eeprom
