; Analog turbidity module
;
; Copy this section into platformio.ini or merge this module branch into a project branch.

[turbidity_analog]
build_flags =
    -D TURBIDITY_PIN=33
    -D TURBIDITY_VCC=3.3
    -D TURBIDITY_ADC_MAX=4096
    -D TURBIDITY_CLEAR_WATER_VOLTAGE=1.780
    -D TURBIDITY_CLEAR_WATER_NTU=0.0
    -D TURBIDITY_TURBID_WATER_VOLTAGE=0.840
    -D TURBIDITY_TURBID_WATER_NTU=600.0
