; DS18B20 temperature module
;
; Copy this section into platformio.ini or merge this module branch into a project branch.

[temperature_ds18b20]
build_flags =
    -D DALLAS_TEMPERATURE_PIN=27
    -Wno-extra-tokens
    -Wno-cpp
lib_deps =
    PaulStoffregen/OneWire
    milesburton/DallasTemperature
